SED-3640-leak-of-resources-for-the-java-agent
exense/step-grid pull request #22
Opened 2024-12-10 16:25 UTC by david-stephan

2025-01-22 12:30 UTC, jeromecomte requested changes
No critical issue found. See remarks

2025-01-22 12:30 UTC, jeromecomte commented on step-grid-api/src/main/java/step/grid/contextbuilder/ApplicationContextBuilder.java
> +			synchronized (ApplicationContextBuilder.this) {
Not sure if it wouldn't be safer to move this synchronized to the method releaseUsage()

2025-01-22 12:30 UTC, jeromecomte commented on step-grid-api/src/main/java/step/grid/contextbuilder/ApplicationContextBuilder.java
> +				logger.debug("Cleanup all application contexts");
"Cleaning up..." would be more suitable

2025-01-22 12:30 UTC, jeromecomte commented on step-grid-api/src/main/java/step/grid/contextbuilder/ApplicationContextBuilder.java
> +					logger.debug("Cleanup application contexts for branch {}", k);
"Cleaning up..." would be more suitable

2025-01-22 12:30 UTC, jeromecomte commented on step-grid-api/src/main/java/step/grid/contextbuilder/ApplicationContextBuilder.java
> +			contextObjects.clear();
contextObjects are only cleared here. No need to clear them somewhere else?

2025-01-22 13:28 UTC, david-stephan commented on step-grid-api/src/main/java/step/grid/contextbuilder/ApplicationContextBuilder.java
> +			boolean cleanable = usage.get() == 0 && childContexts.isEmpty() && descriptor != null;
Well if any of the children is not ready for cleanup (i.e. usage is > 0 )

2025-01-22 14:53 UTC, jeromecomte commented on step-grid-api/src/main/java/step/grid/contextbuilder/ApplicationContextBuilder.java
> +			boolean cleanable = usage.get() == 0 && childContexts.isEmpty() && descriptor != null;
As discussed, we should check if this should be handled as error case and logged accordingly...

2025-01-22 14:55 UTC, david-stephan commented on step-grid-api/src/main/java/step/grid/filemanager/AbstractFileManager.java
> +				if (fileManagerConfiguration.isCleanupJobEnabled() && getCacheTTLms() == 0 && currentUsage == 0 && cachedFileVersion.isCleanable()) {
Well according to the configuration:
`fileManagerConfiguration:
  # enable or disable the cleanup (true by default)
  cleanupJobEnabled: true
  # define file that are eligible for cleanup based on their last access time (default 120 minutes)
  cleanupLastAccessTimeThresholdMinutes: 0
  # define the frequency of the cleanup job in minutes (default 60)
  cleanupIntervalMinutes: 1`
I think one would not expect the cleanup to happen if the clean job is disabled even when setting a TTL of 0.

2025-01-22 15:10 UTC, david-stephan commented on step-grid-api/src/main/java/step/grid/filemanager/AbstractFileManager.java
>  			synchronized (versionCache) {
releaseFileVersionFromCache needs to synchronize on this cache entry to decrement and get the usage count and finally call removeFileVersion if applicable within the same synchronization block. Other caller of removeFileVersion do not need to synchronize before calling removeFileVersion, so the synchronization still has to be done directly in removeFileVersion

2025-01-22 15:23 UTC, david-stephan commented on step-grid-api/src/main/java/step/grid/contextbuilder/ApplicationContextBuilder.java
> +			synchronized (ApplicationContextBuilder.this) {
The synchronization is only required when actually doing the cleanup, i.e. when usage reach 0. I don't see risk with this implementation since we're using atomitc integer and redo a check usage.get() == 0 in the synchronized block

2025-01-22 15:27 UTC, david-stephan commented on step-grid-api/src/main/java/step/grid/contextbuilder/ApplicationContextBuilder.java
> +			contextObjects.clear();
This is legacy code (was just moved to a function). from my understanding, I don't think it needs to be "cleared" in other conditions.

2025-01-22 15:50 UTC, jeromecomte commented on step-grid-api/src/main/java/step/grid/filemanager/AbstractFileManager.java
> +				if (fileManagerConfiguration.isCleanupJobEnabled() && getCacheTTLms() == 0 && currentUsage == 0 && cachedFileVersion.isCleanable()) {
Agree. The property name "cleanupJobEnabled" might just be a bit misleading (as the file is deleted directy upon release and not by the job if the ttl is set to 0.

2025-01-22 16:14 UTC, david-stephan commented on step-grid-api/src/main/java/step/grid/filemanager/AbstractFileManager.java
> +				if (fileManagerConfiguration.isCleanupJobEnabled() && getCacheTTLms() == 0 && currentUsage == 0 && cachedFileVersion.isCleanable()) {
you're right, I refactored to cleanupEnabled, I started to also update the KB accordingly.

2025-01-24 08:51 UTC, jeromecomte approved these changes
Approving with a minor comment

2025-01-24 08:51 UTC, jeromecomte commented on step-grid-api/src/main/java/step/grid/agent/tokenpool/TokenReservationSession.java
> +    public <T extends AutoCloseable> void closeWithSession(T closeable) {
Very minor but the method name is a bit misleading as it suggests an immediate action "close". Replacing by an explicit method name "trackObjectToBeClosedWithSession" or similar could make it easier to understand..

2025-02-03 12:31 UTC, merged